<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>
    
    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
      <PackageReference Include="MailKit" Version="4.17.0" />
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql" Version="10.0.3" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
      <PackageReference Include="Scalar.AspNetCore" Version="2.16.17" />
      <PackageReference Include="SendGrid" Version="9.29.3" />
      <PackageReference Include="SendGrid.Extensions.DependencyInjection" Version="1.0.1" />
      <PackageReference Include="Serilog" Version="4.4.1-dev-02443" />
      <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
      <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
      <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
      <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
      <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />
    </ItemGroup>

</Project>
